version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: DryIoc.dll
    versions:
    - 4.7.4
    - 4.7.5
  - dependency-name: Microsoft.EntityFrameworkCore.InMemory
    versions:
    - 5.0.4
  - dependency-name: Moq
    versions:
    - 4.16.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
  - dependency-name: Microsoft.NETCore.UniversalWindowsPlatform
    versions:
    - 6.2.11
